export const DEFAULT_PLAYBOOKS = [
  {
    id: 'PB-0001',
    name: 'Malware / Virus Detection',
    description: 'SOP respons saat ditemukan indikasi malware, virus, trojan, atau rootkit di host.',
    icon: 'malware',
    triggers: [
      { type: 'rule_group', value: 'malware' },
      { type: 'rule_group', value: 'virus' },
      { type: 'rule_group', value: 'trojans' },
      { type: 'rule_group', value: 'rootkit' },
    ],
    steps: [
      { id: 's1', order: 1, title: 'Isolasi host dari jaringan', category: 'containment', requiresEvidence: true, estimatedMinutes: 5, description: 'Block host di firewall/NAC/switch port. Dokumentasikan waktu isolasi.' },
      { id: 's2', order: 2, title: 'Snapshot / memory dump', category: 'identification', requiresEvidence: true, estimatedMinutes: 15, description: 'Snapshot VM atau memory dump sebelum cleanup untuk keperluan forensik.' },
      { id: 's3', order: 3, title: 'Identifikasi malware dan IOC', category: 'identification', requiresEvidence: true, estimatedMinutes: 20, description: 'Catat hash file, IP C2, registry key, proses mencurigakan. Cek di VirusTotal.' },
      { id: 's4', order: 4, title: 'Scan offline dengan AV terbaru', category: 'eradication', requiresEvidence: false, estimatedMinutes: 45, description: 'Boot ke rescue disk, update definisi, scan full.' },
      { id: 's5', order: 5, title: 'Eradikasi dan cleanup', category: 'eradication', requiresEvidence: true, estimatedMinutes: 30, description: 'Hapus file malware, rollback registry, patch entry point yang dieksploitasi.' },
      { id: 's6', order: 6, title: 'Verifikasi dan restore layanan', category: 'recovery', requiresEvidence: false, estimatedMinutes: 20, description: 'Pastikan malware sudah bersih, restore dari backup clean jika perlu.' },
      { id: 's7', order: 7, title: 'Notifikasi dan eskalasi', category: 'containment', requiresEvidence: false, estimatedMinutes: 10, description: 'Informasikan ke manajemen dan pihak terkait sesuai policy eskalasi.' },
      { id: 's8', order: 8, title: 'Dokumentasi lessons learned', category: 'lessons', requiresEvidence: false, estimatedMinutes: 30, description: 'Tulis laporan, update playbook, review rule detection.' },
    ],
    createdAt: '2026-04-13T00:00:00Z',
    updatedAt: '2026-04-13T00:00:00Z',
    createdBy: 'system',
    isDefault: true,
    isActive: true,
  },
  {
    id: 'PB-0002',
    name: 'Brute Force / Authentication Attack',
    description: 'SOP respons untuk serangan brute force dan percobaan autentikasi tidak sah.',
    icon: 'auth',
    triggers: [
      { type: 'rule_group', value: 'authentication_failed' },
      { type: 'rule_group', value: 'authentication_success' },
      { type: 'rule_group', value: 'invalid_login' },
      { type: 'rule_group', value: 'brute_force' },
    ],
    steps: [
      { id: 's1', order: 1, title: 'Block IP sumber di firewall', category: 'containment', requiresEvidence: true, estimatedMinutes: 5, description: 'Tambahkan IP attacker ke deny list. Gunakan Active Response Wazuh jika belum.' },
      { id: 's2', order: 2, title: 'Audit akun yang diserang', category: 'identification', requiresEvidence: false, estimatedMinutes: 10, description: 'Cek apakah ada login sukses setelah serangan. Review last login time.' },
      { id: 's3', order: 3, title: 'Reset kredensial jika perlu', category: 'eradication', requiresEvidence: false, estimatedMinutes: 5, description: 'Jika akun dikompromis, segera reset password dan invalidate session.' },
      { id: 's4', order: 4, title: 'Enable MFA pada akun target', category: 'recovery', requiresEvidence: false, estimatedMinutes: 15, description: 'Aktifkan MFA jika belum ada. Review policy password.' },
      { id: 's5', order: 5, title: 'Review dan update firewall rules', category: 'recovery', requiresEvidence: true, estimatedMinutes: 20, description: 'Tambahkan rate limiting, geo-blocking jika diperlukan.' },
      { id: 's6', order: 6, title: 'Dokumentasi', category: 'lessons', requiresEvidence: false, estimatedMinutes: 15, description: 'Catat IP, waktu, jumlah attempt, outcome.' },
    ],
    createdAt: '2026-04-13T00:00:00Z',
    updatedAt: '2026-04-13T00:00:00Z',
    createdBy: 'system',
    isDefault: true,
    isActive: true,
  },
  {
    id: 'PB-0003',
    name: 'Critical Vulnerability Detected',
    description: 'SOP respons saat ditemukan kerentanan kritis pada host.',
    icon: 'vuln',
    triggers: [
      { type: 'rule_group', value: 'vulnerability-detector' },
      { type: 'severity', value: 'Critical' },
    ],
    steps: [
      { id: 's1', order: 1, title: 'Verifikasi vulnerability dan scope', category: 'identification', requiresEvidence: false, estimatedMinutes: 10, description: 'Konfirmasi CVE, CVSS score, affected packages. Cek NVD untuk detail.' },
      { id: 's2', order: 2, title: 'Assess exploitability', category: 'identification', requiresEvidence: false, estimatedMinutes: 15, description: 'Apakah exploit sudah publik? Apakah host exposed ke internet? Prioritaskan.' },
      { id: 's3', order: 3, title: 'Apply patch / update package', category: 'eradication', requiresEvidence: true, estimatedMinutes: 30, description: 'Update package ke versi yang sudah dipatch. Test di staging dulu jika ada.' },
      { id: 's4', order: 4, title: 'Verifikasi patch berhasil', category: 'eradication', requiresEvidence: true, estimatedMinutes: 10, description: 'Re-scan dan pastikan vulnerability tidak muncul lagi.' },
      { id: 's5', order: 5, title: 'Update semua host yang affected', category: 'recovery', requiresEvidence: false, estimatedMinutes: 60, description: 'Cek apakah hosts lain juga terpengaruh CVE yang sama. Patch massal.' },
      { id: 's6', order: 6, title: 'Dokumentasi perubahan', category: 'lessons', requiresEvidence: false, estimatedMinutes: 15, description: 'Catat versi sebelum dan sesudah, waktu patch, siapa yang melakukan.' },
    ],
    createdAt: '2026-04-13T00:00:00Z',
    updatedAt: '2026-04-13T00:00:00Z',
    createdBy: 'system',
    isDefault: true,
    isActive: true,
  },
  {
    id: 'PB-0004',
    name: 'File Integrity Violation (FIM)',
    description: 'SOP respons saat Syscheck mendeteksi perubahan file yang mencurigakan.',
    icon: 'fim',
    triggers: [
      { type: 'rule_group', value: 'syscheck' },
      { type: 'rule_group', value: 'fim' },
    ],
    steps: [
      { id: 's1', order: 1, title: 'Identifikasi file yang berubah', category: 'identification', requiresEvidence: true, estimatedMinutes: 10, description: 'Catat path, hash lama vs baru, waktu perubahan, user yang melakukan.' },
      { id: 's2', order: 2, title: 'Tentukan apakah perubahan authorized', category: 'identification', requiresEvidence: false, estimatedMinutes: 10, description: 'Cek change management log. Apakah ada maintenance window atau deployment?' },
      { id: 's3', order: 3, title: 'Jika unauthorized: isolasi dan investigasi', category: 'containment', requiresEvidence: true, estimatedMinutes: 20, description: 'Treat sebagai potential compromise. Ikuti alur Malware Response jika perlu.' },
      { id: 's4', order: 4, title: 'Restore file dari backup bersih', category: 'eradication', requiresEvidence: false, estimatedMinutes: 15, description: 'Kembalikan file ke versi sebelum perubahan dari backup yang dipercaya.' },
      { id: 's5', order: 5, title: 'Review dan update FIM baseline', category: 'recovery', requiresEvidence: false, estimatedMinutes: 20, description: 'Jika perubahan authorized, update baseline Syscheck. Jika tidak, investigate lebih dalam.' },
      { id: 's6', order: 6, title: 'Dokumentasi', category: 'lessons', requiresEvidence: false, estimatedMinutes: 10, description: 'Catat file yang berubah, keputusan yang diambil, action yang dilakukan.' },
    ],
    createdAt: '2026-04-13T00:00:00Z',
    updatedAt: '2026-04-13T00:00:00Z',
    createdBy: 'system',
    isDefault: true,
    isActive: true,
  },
  {
    id: 'PB-0005',
    name: 'Suspicious Process / Rootkit',
    description: 'SOP respons saat ditemukan proses mencurigakan atau indikasi rootkit.',
    icon: 'rootkit',
    triggers: [
      { type: 'rule_group', value: 'rootcheck' },
      { type: 'rule_group', value: 'process_monitor' },
    ],
    steps: [
      { id: 's1', order: 1, title: 'Dump proses mencurigakan', category: 'identification', requiresEvidence: true, estimatedMinutes: 10, description: 'Capture output ps aux, netstat, lsof. Catat PID, parent PID, network connections.' },
      { id: 's2', order: 2, title: 'Hash binary dan cek VirusTotal', category: 'identification', requiresEvidence: true, estimatedMinutes: 10, description: 'md5sum / sha256sum binary. Submit ke VirusTotal. Cek reputation IP yang terhubung.' },
      { id: 's3', order: 3, title: 'Isolasi host', category: 'containment', requiresEvidence: false, estimatedMinutes: 5, description: 'Isolasi dari jaringan untuk mencegah lateral movement atau data exfiltration.' },
      { id: 's4', order: 4, title: 'Memory forensics', category: 'identification', requiresEvidence: true, estimatedMinutes: 30, description: 'Ambil memory dump dengan Volatility. Cari injected code, hidden processes.' },
      { id: 's5', order: 5, title: 'Eradikasi dan rebuild jika perlu', category: 'eradication', requiresEvidence: false, estimatedMinutes: 60, description: 'Jika rootkit terkonfirmasi, rebuild host dari clean image lebih aman daripada cleanup.' },
      { id: 's6', order: 6, title: 'Hardening dan monitoring', category: 'recovery', requiresEvidence: false, estimatedMinutes: 30, description: 'Aktifkan audit logging, deploy HIDS lebih agresif, review sudoers dan cron.' },
    ],
    createdAt: '2026-04-13T00:00:00Z',
    updatedAt: '2026-04-13T00:00:00Z',
    createdBy: 'system',
    isDefault: true,
    isActive: true,
  },
  {
    id: 'PB-0006',
    name: 'General High Alert',
    description: 'SOP respons umum untuk alert level High yang tidak termasuk kategori spesifik.',
    icon: 'generic',
    triggers: [
      { type: 'severity', value: 'High' },
    ],
    steps: [
      { id: 's1', order: 1, title: 'Triage dan kategorisasi alert', category: 'identification', requiresEvidence: false, estimatedMinutes: 10, description: 'Tentukan apakah alert ini true positive atau false positive. Kategorikan jenis insiden.' },
      { id: 's2', order: 2, title: 'Kumpulkan konteks tambahan', category: 'identification', requiresEvidence: true, estimatedMinutes: 15, description: 'Gather log tambahan dari agent, cek timeline event sekitar waktu alert.' },
      { id: 's3', order: 3, title: 'Eskalasi atau handle', category: 'containment', requiresEvidence: false, estimatedMinutes: 10, description: 'Jika di luar kemampuan, eskalasi ke senior analyst atau team lead.' },
      { id: 's4', order: 4, title: 'Dokumentasi tindakan', category: 'lessons', requiresEvidence: false, estimatedMinutes: 10, description: 'Catat semua langkah yang sudah diambil dan hasilnya.' },
    ],
    createdAt: '2026-04-13T00:00:00Z',
    updatedAt: '2026-04-13T00:00:00Z',
    createdBy: 'system',
    isDefault: true,
    isActive: true,
  },
]
